#include "../../firmware/main-deck-p4/components/control_link/include/control_link.h"

int p4_btn_eject(void) { return BTN_EJECT; }
int p4_btn_track_prev(void) { return BTN_TRACK_PREV; }
int p4_btn_track_next(void) { return BTN_TRACK_NEXT; }
int p4_btn_search_back(void) { return BTN_SEARCH_BACK; }
int p4_btn_search_fwd(void) { return BTN_SEARCH_FWD; }
int p4_btn_cue(void) { return BTN_CUE; }
int p4_btn_play(void) { return BTN_PLAY; }
int p4_btn_master_tempo(void) { return BTN_MASTER_TEMPO; }
int p4_btn_load(void) { return BTN_LOAD; }
int p4_btn_count(void) { return BTN_COUNT; }
int p4_ctrl_ev_jog(void) { return CTRL_EV_JOG; }
int p4_ctrl_ev_browse(void) { return CTRL_EV_BROWSE; }
int p4_ctrl_ev_state(void) { return CTRL_EV_STATE; }
int p4_ctrl_type_state(void) { return CTRL_TYPE_STATE; }
int p4_ctrl_id_flx4_connection(void) { return CTRL_ID_FLX4_CONNECTION; }
int p4_ctrl_id_smart_cfx(void) { return CTRL_ID_SMART_CFX; }
int p4_ctrl_id_smart_fader(void) { return CTRL_ID_SMART_FADER; }
int p4_ctrl_id_smart_cfx_shift(void) { return CTRL_ID_SMART_CFX_SHIFT; }
int p4_ctrl_id_smart_fader_shift(void) { return CTRL_ID_SMART_FADER_SHIFT; }
int p4_ctrl_id_beat_fx_select_next(void) { return CTRL_ID_BEAT_FX_SELECT_NEXT; }
int p4_ctrl_id_beat_fx_clear(void) { return CTRL_ID_BEAT_FX_CLEAR; }
int p4_ctrl_id_deck1_shift(void) { return CTRL_ID_DECK1_SHIFT; }
int p4_ctrl_id_deck2_to_start(void) { return CTRL_ID_DECK2_TO_START; }
int p4_ctrl_id_deck1_sync(void) { return CTRL_ID_DECK1_SYNC; }
int p4_ctrl_id_deck2_tempo_range(void) { return CTRL_ID_DECK2_TEMPO_RANGE; }
int p4_ctrl_id_deck2_pad_action(void) { return CTRL_ID_DECK2_PAD_ACTION; }
int p4_ctrl_id_ch1_trim(void) { return CTRL_ID_CH1_TRIM; }
int p4_ctrl_id_headphone_mix(void) { return CTRL_ID_HEADPHONE_MIX; }
int p4_ctrl_id_headphone_level(void) { return CTRL_ID_HEADPHONE_LEVEL; }
int p4_ctrl_id_master_volume(void) { return CTRL_ID_MASTER_VOLUME; }
int p4_ctrl_id_master_cue(void) { return CTRL_ID_MASTER_CUE; }
int p4_ctrl_id_deck1_jog_search(void) { return CTRL_ID_DECK1_JOG_SEARCH; }
int p4_ctrl_id_deck2_jog_search_touch(void) { return CTRL_ID_DECK2_JOG_SEARCH_TOUCH; }
int p4_ctrl_id_browse_shift_delta(void) { return CTRL_ID_BROWSE_SHIFT_DELTA; }
int p4_ctrl_id_browse_shift_press(void) { return CTRL_ID_BROWSE_SHIFT_PRESS; }
int p4_ctrl_id_shift_load_deck1(void) { return CTRL_ID_SHIFT_LOAD_DECK1; }
int p4_ctrl_id_shift_load_deck2(void) { return CTRL_ID_SHIFT_LOAD_DECK2; }
int p4_ctrl_id_deck1_ext_action(void) { return CTRL_ID_DECK1_EXT_ACTION; }
int p4_ctrl_id_deck2_ext_action(void) { return CTRL_ID_DECK2_EXT_ACTION; }
int p4_ctrl_deck_ext_action_censor(void) { return CTRL_DECK_EXT_ACTION_CENSOR; }
int p4_ctrl_deck_ext_action_sync_master(void) { return CTRL_DECK_EXT_ACTION_SYNC_MASTER; }
int p4_ctrl_deck_ext_action_reloop_stop(void) { return CTRL_DECK_EXT_ACTION_RELOOP_STOP; }
int p4_ctrl_deck_ext_action_loop_adjust_in(void) { return CTRL_DECK_EXT_ACTION_LOOP_ADJUST_IN; }
int p4_ctrl_deck_ext_action_loop_adjust_out(void) { return CTRL_DECK_EXT_ACTION_LOOP_ADJUST_OUT; }
int p4_ctrl_deck_ext_action_quantize(void) { return CTRL_DECK_EXT_ACTION_QUANTIZE; }
int p4_led_vu_meter(void) { return LED_VU_METER; }
int p4_led_pad_mode_hot_cue(void) { return LED_PAD_MODE_HOT_CUE; }
int p4_led_pad_mode_key_shift(void) { return LED_PAD_MODE_KEY_SHIFT; }
int p4_led_sync(void) { return LED_SYNC; }
int p4_led_loop_in(void) { return LED_LOOP_IN; }
int p4_led_loop_out(void) { return LED_LOOP_OUT; }
int p4_led_master_cue(void) { return LED_MASTER_CUE; }
int p4_ctrl_flx4_disconnected(void) { return CTRL_FLX4_DISCONNECTED; }
int p4_ctrl_flx4_connected(void) { return CTRL_FLX4_CONNECTED; }
