#include "../../firmware/control-board-s3/components/panel_io/include/panel_io.h"
#include "../../firmware/control-board-s3/components/control_link/include/control_link.h"

int s3_btn_eject(void) { return BTN_EJECT; }
int s3_btn_track_prev(void) { return BTN_TRACK_PREV; }
int s3_btn_track_next(void) { return BTN_TRACK_NEXT; }
int s3_btn_search_back(void) { return BTN_SEARCH_BACK; }
int s3_btn_search_fwd(void) { return BTN_SEARCH_FWD; }
int s3_btn_cue(void) { return BTN_CUE; }
int s3_btn_play(void) { return BTN_PLAY; }
int s3_btn_master_tempo(void) { return BTN_MASTER_TEMPO; }
int s3_btn_load(void) { return BTN_LOAD; }
int s3_btn_count(void) { return BTN_COUNT; }
int s3_panel_ev_jog(void) { return PANEL_EV_JOG; }
int s3_panel_ev_browse(void) { return PANEL_EV_BROWSE; }
int s3_control_link_uart_tx_gpio(void) { return CONTROL_LINK_UART_TX_GPIO; }
int s3_control_link_uart_rx_gpio(void) { return CONTROL_LINK_UART_RX_GPIO; }
int s3_ctrl_id_deck1_play(void) { return CTRL_ID_DECK1_PLAY; }
int s3_ctrl_id_deck2_cue(void) { return CTRL_ID_DECK2_CUE; }
int s3_ctrl_id_deck1_tempo(void) { return CTRL_ID_DECK1_TEMPO; }
int s3_ctrl_id_ch1_volume(void) { return CTRL_ID_CH1_VOLUME; }
int s3_ctrl_id_crossfader(void) { return CTRL_ID_CROSSFADER; }
int s3_ctrl_id_browse_delta(void) { return CTRL_ID_BROWSE_DELTA; }
int s3_ctrl_id_load_deck2(void) { return CTRL_ID_LOAD_DECK2; }
int s3_ctrl_id_shift_load_deck1(void) { return CTRL_ID_SHIFT_LOAD_DECK1; }
int s3_ctrl_id_shift_load_deck2(void) { return CTRL_ID_SHIFT_LOAD_DECK2; }
int s3_ctrl_id_browse_press(void) { return CTRL_ID_BROWSE_PRESS; }
int s3_ctrl_type_state(void) { return CTRL_TYPE_STATE; }
int s3_ctrl_id_flx4_connection(void) { return CTRL_ID_FLX4_CONNECTION; }
int s3_ctrl_id_smart_cfx(void) { return CTRL_ID_SMART_CFX; }
int s3_ctrl_id_smart_fader(void) { return CTRL_ID_SMART_FADER; }
int s3_ctrl_id_smart_cfx_shift(void) { return CTRL_ID_SMART_CFX_SHIFT; }
int s3_ctrl_id_smart_fader_shift(void) { return CTRL_ID_SMART_FADER_SHIFT; }
int s3_ctrl_id_beat_fx_select_next(void) { return CTRL_ID_BEAT_FX_SELECT_NEXT; }
int s3_ctrl_id_beat_fx_clear(void) { return CTRL_ID_BEAT_FX_CLEAR; }
int s3_ctrl_id_beat_fx_beat_dec_shift(void) { return CTRL_ID_BEAT_FX_BEAT_DEC_SHIFT; }
int s3_ctrl_id_beat_fx_beat_inc_shift(void) { return CTRL_ID_BEAT_FX_BEAT_INC_SHIFT; }
int s3_ctrl_id_deck1_shift(void) { return CTRL_ID_DECK1_SHIFT; }
int s3_ctrl_id_deck2_to_start(void) { return CTRL_ID_DECK2_TO_START; }
int s3_ctrl_id_deck1_sync(void) { return CTRL_ID_DECK1_SYNC; }
int s3_ctrl_id_deck2_tempo_range(void) { return CTRL_ID_DECK2_TEMPO_RANGE; }
int s3_ctrl_id_deck2_pad_action(void) { return CTRL_ID_DECK2_PAD_ACTION; }
int s3_ctrl_id_ch1_trim(void) { return CTRL_ID_CH1_TRIM; }
int s3_ctrl_id_headphone_mix(void) { return CTRL_ID_HEADPHONE_MIX; }
int s3_ctrl_id_headphone_level(void) { return CTRL_ID_HEADPHONE_LEVEL; }
int s3_ctrl_id_master_volume(void) { return CTRL_ID_MASTER_VOLUME; }
int s3_ctrl_id_master_cue(void) { return CTRL_ID_MASTER_CUE; }
int s3_ctrl_id_deck1_jog_search(void) { return CTRL_ID_DECK1_JOG_SEARCH; }
int s3_ctrl_id_deck2_jog_search_touch(void) { return CTRL_ID_DECK2_JOG_SEARCH_TOUCH; }
int s3_ctrl_id_browse_shift_delta(void) { return CTRL_ID_BROWSE_SHIFT_DELTA; }
int s3_ctrl_id_browse_shift_press(void) { return CTRL_ID_BROWSE_SHIFT_PRESS; }
int s3_ctrl_id_deck1_ext_action(void) { return CTRL_ID_DECK1_EXT_ACTION; }
int s3_ctrl_id_deck2_ext_action(void) { return CTRL_ID_DECK2_EXT_ACTION; }
int s3_ctrl_deck_ext_action_censor(void) { return CTRL_DECK_EXT_ACTION_CENSOR; }
int s3_ctrl_deck_ext_action_sync_master(void) { return CTRL_DECK_EXT_ACTION_SYNC_MASTER; }
int s3_ctrl_deck_ext_action_reloop_stop(void) { return CTRL_DECK_EXT_ACTION_RELOOP_STOP; }
int s3_ctrl_deck_ext_action_loop_adjust_in(void) { return CTRL_DECK_EXT_ACTION_LOOP_ADJUST_IN; }
int s3_ctrl_deck_ext_action_loop_adjust_out(void) { return CTRL_DECK_EXT_ACTION_LOOP_ADJUST_OUT; }
int s3_ctrl_deck_ext_action_quantize(void) { return CTRL_DECK_EXT_ACTION_QUANTIZE; }
int s3_led_vu_meter(void) { return LED_VU_METER; }
int s3_led_pad_mode_hot_cue(void) { return LED_PAD_MODE_HOT_CUE; }
int s3_led_pad_mode_key_shift(void) { return LED_PAD_MODE_KEY_SHIFT; }
int s3_led_sync(void) { return LED_SYNC; }
int s3_led_loop_in(void) { return LED_LOOP_IN; }
int s3_led_loop_out(void) { return LED_LOOP_OUT; }
int s3_led_master_cue(void) { return LED_MASTER_CUE; }
int s3_led_beat_jump_pad_1(void) { return LED_BEAT_JUMP_PAD_1; }
int s3_led_beat_jump_pad_8(void) { return LED_BEAT_JUMP_PAD_8; }
int s3_led_beat_jump_shift_helper_7(void) { return LED_BEAT_JUMP_SHIFT_HELPER_7; }
int s3_led_beat_jump_shift_helper_8(void) { return LED_BEAT_JUMP_SHIFT_HELPER_8; }
int s3_ctrl_flx4_disconnected(void) { return CTRL_FLX4_DISCONNECTED; }
int s3_ctrl_flx4_connected(void) { return CTRL_FLX4_CONNECTED; }
