# Resolve before ESP-IDF generates the fixed 32-byte app descriptor.
# Release tags are board-family ancestry roots; derived distribution tags
# must never become roots of another git-describe chain.
function(pajoniiir_resolve_version tag_pattern)
    find_package(Git REQUIRED)
    if(PAJONIIIR_RELEASE_BUILD AND NOT PAJONIIIR_RELEASE_VERSION)
        message(FATAL_ERROR "Release builds require PAJONIIIR_RELEASE_VERSION")
    endif()
    if(PAJONIIIR_RELEASE_VERSION)
        set(version "${PAJONIIIR_RELEASE_VERSION}")
        if(tag_pattern STREQUAL "M3-*")
            if(NOT version MATCHES "^M3-[0-9]+(-[0-9]+-g[0-9a-f]+)*$")
                message(FATAL_ERROR "M3 requires a numeric M3 release version")
            endif()
            string(REGEX REPLACE "^M3-([0-9]+).*" "\\1" milestone "${version}")
            if(milestone GREATER 4294967295)
                message(FATAL_ERROR "M3 release number exceeds the runtime version contract")
            endif()
        elseif(NOT version MATCHES "^M2\\.[0-9]+(-[0-9]+-g[0-9a-f]+)*$")
            message(FATAL_ERROR "JC boards require an M2 release version")
        endif()
    else()
        execute_process(COMMAND "${GIT_EXECUTABLE}" describe --tags --dirty --exclude "*-g*"
            --match "${tag_pattern}" WORKING_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}"
            RESULT_VARIABLE result OUTPUT_VARIABLE version
            ERROR_VARIABLE describe_error OUTPUT_STRIP_TRAILING_WHITESPACE)
        if(NOT result EQUAL 0)
            if(NOT tag_pattern STREQUAL "M3-*")
                message(FATAL_ERROR "Unable to resolve PROJECT_VER: ${describe_error}")
            endif()
            execute_process(COMMAND "${GIT_EXECUTABLE}" rev-parse --short=12 HEAD
                WORKING_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}"
                RESULT_VARIABLE result OUTPUT_VARIABLE sha OUTPUT_STRIP_TRAILING_WHITESPACE)
            if(NOT result EQUAL 0)
                message(FATAL_ERROR "Cannot identify M3 development source")
            endif()
            set(version "M3-dev-g${sha}")
            execute_process(COMMAND "${GIT_EXECUTABLE}" status --porcelain
                WORKING_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}"
                RESULT_VARIABLE result OUTPUT_VARIABLE dirty)
            if(NOT result EQUAL 0)
                message(FATAL_ERROR "Cannot verify source cleanliness")
            endif()
            if(dirty)
                string(APPEND version "-dirty")
            endif()
        endif()
    endif()
    string(LENGTH "${version}" PAJONIIIR_PROJECT_VER_BYTES)
    if(PAJONIIIR_PROJECT_VER_BYTES GREATER 31)
        message(FATAL_ERROR "ESP-IDF app descriptors allow at most 31 bytes")
    endif()
    string(REGEX MATCHALL "-g[0-9a-f]+" hashes "${version}")
    foreach(hash IN LISTS hashes)
        string(LENGTH "${hash}" hash_bytes)
        if(hash_bytes LESS 9)
            message(FATAL_ERROR "Release ancestry hashes need at least seven hex digits")
        endif()
    endforeach()
    string(REGEX MATCHALL "-[0-9]+-g" distances "${version}")
    set(total_distance 0)
    foreach(segment IN LISTS distances)
        string(REGEX REPLACE "^-([0-9]+)-g$" "\\1" distance "${segment}")
        if(distance GREATER 4294967295)
            message(FATAL_ERROR "Release ancestry distance exceeds the runtime version contract")
        endif()
        math(EXPR total_distance "${total_distance} + ${distance}")
        if(total_distance GREATER 4294967295)
            message(FATAL_ERROR "Release ancestry sum exceeds the runtime version contract")
        endif()
    endforeach()
    if(PAJONIIIR_RELEASE_BUILD)
        execute_process(COMMAND "${GIT_EXECUTABLE}" status --porcelain
            WORKING_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}"
            RESULT_VARIABLE result OUTPUT_VARIABLE dirty)
        if(NOT result EQUAL 0 OR dirty)
            message(FATAL_ERROR "Release builds require a clean committed source")
        endif()
    endif()
    set(PROJECT_VER "${version}" PARENT_SCOPE)
endfunction()
