/* Asset generation only; firmware never parses SVG or allocates a logo buffer.
 * Requires Node.js and sharp (also available in the bundled workspace runtime).
 * Run: node tools/generate_default_artwork.cjs [preview-directory]
 */
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const sharp = require('sharp');

async function main() {
    const ui = path.resolve(__dirname, '../firmware/p4-core/components/ui');
    const svg = fs.readFileSync(path.join(ui, 'assets/default_artwork.svg'));
    const hash = crypto.createHash('sha256').update(svg).digest('hex');
    const lines = [
        '/* Generated by tools/generate_default_artwork.cjs; do not hand-edit pixels.',
        ` * Source SVG SHA-256: ${hash}`, ' */',
        '#include "ui_artwork_placeholder.h"', '#include "ui_artwork_thumb.h"', ''
    ];
    for (const [kind, size] of [['row', 40], ['deck', 34]]) {
        const raw = await sharp(svg, { density: 192 }).resize(size, size)
            .flatten({ background: '#000000' }).removeAlpha().raw().toBuffer();
        if (raw.length !== size * size * 3) throw new Error('Expected tightly packed RGB pixels');
        const rgb565 = [];
        const preview = Buffer.alloc(raw.length);
        for (let i = 0; i < raw.length; i += 3) {
            const value = ((raw[i] >> 3) << 11) | ((raw[i + 1] >> 2) << 5) | (raw[i + 2] >> 3);
            rgb565.push(`0x${value.toString(16).padStart(4, '0')}`);
            preview[i] = Math.round(((value >> 11) & 31) * 255 / 31);
            preview[i + 1] = Math.round(((value >> 5) & 63) * 255 / 63);
            preview[i + 2] = Math.round((value & 31) * 255 / 31);
        }
        lines.push(`_Static_assert(UI_ARTWORK_${kind.toUpperCase()}_PX == ${size}, "Regenerate artwork after thumbnail resize");`);
        lines.push(`_Alignas(4) static const uint16_t s_${kind}_pixels[${size * size}] = {`);
        for (let i = 0; i < rgb565.length; i += 12)
            lines.push('    ' + rgb565.slice(i, i + 12).join(', ') + ',');
        lines.push('};', `const lv_image_dsc_t ui_artwork_placeholder_${kind} = {`,
            '    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,',
            `                .w = ${size}, .h = ${size}, .stride = ${size * 2} },`,
            `    .data_size = sizeof(s_${kind}_pixels),`,
            `    .data = (const uint8_t *)s_${kind}_pixels,`, '};', '');
        if (process.argv[2]) {
            fs.mkdirSync(process.argv[2], { recursive: true });
            await sharp(preview, { raw: { width: size, height: size, channels: 3 } })
                .png().toFile(path.join(process.argv[2], `default_artwork_${kind}.png`));
        }
    }
    fs.writeFileSync(path.join(ui, 'ui_artwork_placeholder.c'), lines.join('\n'));
    console.log('Generated read-only artwork: 40x40 + 34x34 RGB565 (5,512 pixel bytes).');
}
main().catch(error => { console.error(error); process.exitCode = 1; });
